[build]
  publish = "."

[[headers]]
  for = "*.exe"
  [headers.values]
    Content-Type = "application/octet-stream"
    Content-Disposition = "attachment"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/download"
  to = "/download.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/"
  status = 200

