version: 2
updates:
  # Enable version updates for npm (combined security and regular updates)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Bigsgotchu"
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    # Allow both security and version updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
        update-type: "security"
    versioning-strategy: increase-if-necessary
    labels:
      - "dependencies"
    # Registry configuration for private packages
    registries:
      - npm-github-packages
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"

# Registry configurations for private packages
registries:
  npm-github-packages:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_TOKEN }}
