/**
 * Plan Execution
 *
 * Executes plans generated by the neural planner.
 * Runs each step through the tool registry.
 */

import { thinkingStream } from '../thinking/thinkingStream.js'
import { toolRegistry } from '../core/toolRegistry.js'
import type { PlanStep, NeuralPlan } from './neuralPlanner.js'

export type ExecutionResult = {
  success: boolean
  planId: string
  stepsCompleted: number
  totalSteps: number
  outputs: string[]
  error?: string
}

/**
 * Execute a neural plan
 */
export async function executePlan(plan: NeuralPlan): Promise<ExecutionResult> {
  const outputs: string[] = []
  let stepsCompleted = 0

  thinkingStream.emit('thinking', {
    type: 'plan_execution',
    status: 'started',
    message: `Executing plan with ${plan.steps.length} steps`,
  })

  for (let i = 0; i < plan.steps.length; i++) {
    const step = plan.steps[i]

    thinkingStream.emit('thinking', {
      type: 'plan_execution',
      status: 'step_start',
      message: `Step ${i + 1}/${plan.steps.length}: ${step.description || step.action}`,
    })

    try {
      const output = await executeStep(step)
      outputs.push(output)
      stepsCompleted++

      thinkingStream.emit('thinking', {
        type: 'plan_execution',
        status: 'step_complete',
        message: `Step ${i + 1} completed`,
        output: output.slice(0, 100),
      })
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error)

      thinkingStream.emit('thinking', {
        type: 'plan_execution',
        status: 'step_error',
        message: `Step ${i + 1} failed: ${errorMsg}`,
      })

      return {
        success: false,
        planId: plan.id,
        stepsCompleted,
        totalSteps: plan.steps.length,
        outputs,
        error: errorMsg,
      }
    }
  }

  thinkingStream.emit('thinking', {
    type: 'plan_execution',
    status: 'completed',
    message: `Plan completed: ${stepsCompleted}/${plan.steps.length} steps`,
  })

  return {
    success: true,
    planId: plan.id,
    stepsCompleted,
    totalSteps: plan.steps.length,
    outputs,
  }
}

/**
 * Execute a single plan step
 */
async function executeStep(step: PlanStep): Promise<string> {
  const tool = toolRegistry.get(step.tool)

  if (!tool) {
    throw new Error(`Tool not found: ${step.tool}`)
  }

  if (typeof tool.execute !== 'function') {
    throw new Error(`Tool ${step.tool} does not have an execute method`)
  }

  // Execute with optional timeout
  const timeout = step.timeout || 60000

  return Promise.race([
    tool.execute(step.action),
    new Promise<string>((_, reject) =>
      setTimeout(() => reject(new Error(`Step timed out after ${timeout}ms`)), timeout)
    ),
  ])
}

/**
 * Execute a plan with progress callbacks
 */
export async function executePlanWithProgress(
  plan: NeuralPlan,
  onProgress?: (step: number, total: number, output: string) => void
): Promise<ExecutionResult> {
  const outputs: string[] = []
  let stepsCompleted = 0

  for (let i = 0; i < plan.steps.length; i++) {
    const step = plan.steps[i]

    try {
      const output = await executeStep(step)
      outputs.push(output)
      stepsCompleted++

      if (onProgress) {
        onProgress(i + 1, plan.steps.length, output)
      }
    } catch (error) {
      return {
        success: false,
        planId: plan.id,
        stepsCompleted,
        totalSteps: plan.steps.length,
        outputs,
        error: error instanceof Error ? error.message : String(error),
      }
    }
  }

  return {
    success: true,
    planId: plan.id,
    stepsCompleted,
    totalSteps: plan.steps.length,
    outputs,
  }
}
