steps:
  # Build the RinaWarp Terminal webapp container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.webapp'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rinawarp-terminal-webapp'
      - '.'
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/rinawarp-terminal-webapp'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'rinawarp-terminal'
      - '--image'
      - 'gcr.io/$PROJECT_ID/rinawarp-terminal-webapp'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '100'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/rinawarp-terminal-webapp'
