[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm install --production"]

[phases.build]
cmds = ["echo 'RinaWarp Terminal - Ready for deployment'"]

[phases.start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
PORT = "8080"
