[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm ci --omit=optional"]

[phases.build]
cmds = ["echo 'RinaWarp Terminal - Clean deployment ready'"]

[phases.start]
cmd = "NODE_OPTIONS='--import ./instrument.mjs' node server.js"

[variables]
NODE_ENV = "production"
PORT = "8080"
NODE_OPTIONS = "--import ./instrument.mjs"
