#!/usr/bin/env node
/*
 * 🧜‍♀️ This file has been automatically modernized by RinaWarp Terminal
 * 2 deprecated pattern(s) replaced with modern alternatives
 * Please review and test the changes
 */

/**
 * Automated URL Fix Script
 * Generated by url-audit.js
 */

const fs = require('node:fs');
const _path = require('node:path');

const fixes = [
  { from: /bigsgotchu\/rinawarp-terminal/gi, to: 'Rinawarp-Terminal/rinawarp-terminal' },
  { from: /https?:\/\/api\.rinawarp\.com/gi, to: 'https://api.rinawarp-terminal.com' },
  { from: /https?:\/\/docs\.rinawarp\.com/gi, to: 'https://docs.rinawarp-terminal.com' },
  { from: /https?:\/\/status\.rinawarp\.com/gi, to: 'https://status.rinawarp-terminal.com' },
  { from: /api-support@rinawarp\.com/gi, to: 'api-support@rinawarp-terminal.com' },
  { from: /github\.com\/Bigsgotchu/gi, to: 'github.com/Rinawarp-Terminal' },
  { from: /v1\.0\.8/gi, to: 'v1.0.19' },
];

const filesToFix = [
  'URL_UPDATE_SUMMARY.md',
  'SOCIAL_MEDIA_MARKETING_TEMPLATES.md',
  'SECURITY.md',
  'README.md',
  'GITHUB_DISCUSSION_CONTENT.md',
  'FINAL_TEST_REPORT.md',
  'BETA_TESTING_EMAIL_TEMPLATES.md',
  'BETA_SALES_ANNOUNCEMENT.md',
  'src/plugins/docs/plugin-api.md',
  'marketing/v1.0.8-social-media.md',
  'marketing/v1.0.8-release-notes.md',
  'marketing/v1.0.8-press-release.md',
  'marketing/v1.0.8-beta-notification.md',
  'functions/node_modules/which/CHANGELOG.md',
  'functions/node_modules/string.prototype.trimstart/CHANGELOG.md',
  'functions/node_modules/string.prototype.trimend/CHANGELOG.md',
  'functions/node_modules/reflect.getprototypeof/CHANGELOG.md',
  'functions/node_modules/is-generator-function/CHANGELOG.md',
  'functions/node_modules/handlebars/release-notes.md',
  'functions/node_modules/flat-cache/changelog.md',
  'functions/node_modules/call-bind/CHANGELOG.md',
  'email-testing-suite/node_modules/which/CHANGELOG.md',
  'email-templates/testing/node_modules/which/CHANGELOG.md',
  'email-templates/testing/node_modules/flat-cache/changelog.md',
  'docs/api-reference.md',
  'docs/SETUP_STATUS.md',
  'docs/CICD_MONITORING_STATUS.md',
  'docs/v1.0.9-planning/COMMUNITY_FEEDBACK_ANALYSIS.md',
  'docs/guides/SETUP.md',
  'docs/guides/QUICKSTART.md',
  'docs/guides/INSTALL.md',
  'beta-testing/BETA_SURVEY_TEMPLATE.md',
  'server.js',
  'server-improvements.js',
  'discord-bot.js',
  'src/plugins/tests/plugin-manager.test.js',
  'src/monitoring/ip-monitor.js',
  'src/community/community-engagement-manager.js',
  'src/api/gateway.js',
  'sdk/javascript/tests/rinawarp-sdk.test.js',
  'sdk/javascript/src/rinawarp-sdk.js',
  'sdk/javascript/examples/basic-usage.js',
  'scripts/url-audit.js',
  'mobile/RinaWarpMonitor/App.js',
  'sdk/javascript/src/rinawarp-sdk.ts',
  'BETA_EMAIL_SIMPLE_RESPONSIVE.html',
  'BETA_EMAIL_SIMPLE.html',
  'website/index.html',
  'public/docs.html',
  'public/blog.html',
  'public/beta-download.html',
  'BETA_EMAIL_PLAIN_TEXT.txt',
  'scripts/monitor-workflows.cjs',
  'scripts/monitor-live.cjs',
  'scripts/check-workflows.cjs',
];

console.log('🔧 Applying automated URL fixes...');

let fixedFiles = 0;
let totalFixes = 0;

for (const file of filesToFix) {
  try {
    let content = fs.readFileSync(file, 'utf8');
    let fileFixed = false;

    for (const fix of fixes) {
      const matches = content.match(fix.from);
      if (matches) {
        content = content.replace(fix.from, fix.to);
        totalFixes += matches.length;
        fileFixed = true;
      }
    }

    if (fileFixed) {
      fs.writeFileSync(file, content, 'utf8');
      fixedFiles++;
      console.log(`✅ Fixed: ${file}`);
    }
  } catch (error) {
    console.warn(`⚠️ Could not fix file: ${file} - ${error.message}`);
  }
}

console.log(`\n🎉 Fixed ${totalFixes} URLs in ${fixedFiles} files`);
console.log('\n⚠️ Please review the changes and test the application!');
