/**
 * Create Agent CLI Command
 *
 * Scaffolds a new agent with default structure and manifest.
 */

import fs from 'fs'
import path from 'path'

interface CreateAgentOptions {
  name: string
  description?: string
  author?: string
  permissions?: string[]
  outputDir?: string
}

/**
 * Default permissions for new agents
 */
const DEFAULT_PERMISSIONS = ['terminal']

/**
 * Create a new agent from template
 */
export async function createAgent(options: CreateAgentOptions): Promise<void> {
  const { name, description, author, permissions, outputDir } = options

  // Validate name (kebab-case)
  if (!/^[a-z0-9-]+$/.test(name)) {
    console.error('Error: Agent name must be kebab-case (lowercase letters, numbers, hyphens)')
    process.exit(1)
  }

  const targetDir = outputDir || name
  const fullPath = path.resolve(targetDir)

  // Check if directory already exists
  if (fs.existsSync(fullPath)) {
    console.error(`Error: Directory already exists: ${fullPath}`)
    process.exit(1)
  }

  // Create directory
  fs.mkdirSync(fullPath, { recursive: true })
  console.log(`Created directory: ${fullPath}`)

  // Create agent.json manifest
  const manifest = {
    name,
    version: '1.0.0',
    entry: 'index.js',
    permissions: permissions || DEFAULT_PERMISSIONS,
    description: description || `Agent: ${name}`,
    author: author || 'developer',
  }

  fs.writeFileSync(path.join(fullPath, 'agent.json'), JSON.stringify(manifest, null, 2), 'utf8')
  console.log('Created: agent.json')

  // Create index.js with template code
  const templateCode = `/**
 * ${name} Agent
 * 
 * This agent is automatically generated by RinaWarp Agent SDK.
 * Edit this file to implement your agent logic.
 * 
 * Available APIs (based on permissions):
 * - api.terminal.run(command) - Execute shell commands
 * - api.filesystem.read(path) - Read files
 * - api.filesystem.write(path, content) - Write files
 * - api.git.status() - Get git status
 * - api.docker.ps() - List containers
 */

export async function run() {
  // Your agent logic here
  console.log("Hello from ${name} agent!");
  
  // Example: Run a terminal command
  // const status = await api.terminal.run("git status");
  // console.log(status);
  
  return "Agent completed";
}

// Export run function for the runtime
export default { run };
`

  fs.writeFileSync(path.join(fullPath, 'index.js'), templateCode, 'utf8')
  console.log('Created: index.js')

  // Create README.md
  const readme = `# ${name} Agent

Generated by RinaWarp Agent SDK v1.0.0

## Permissions

${(permissions || DEFAULT_PERMISSIONS).map((p) => `- ${p}`).join('\n')}

## Usage

\`\`\`bash
# Test locally
rina test ${name}

# Publish to marketplace
rina publish
\`\`\`

## Development

Edit \`index.js\` to implement your agent logic. The agent has access to:

${(permissions || DEFAULT_PERMISSIONS).includes('terminal') ? '- `api.terminal.run(cmd)` - Run shell commands\n' : ''}${permissions?.includes('filesystem:read') || DEFAULT_PERMISSIONS.includes('filesystem:read') ? '- `api.filesystem.read(path)` - Read files\n' : ''}${permissions?.includes('filesystem:write') || DEFAULT_PERMISSIONS.includes('filesystem:write') ? '- `api.filesystem.write(path, content)` - Write files\n' : ''}
`

  fs.writeFileSync(path.join(fullPath, 'README.md'), readme, 'utf8')
  console.log('Created: README.md')

  console.log(`\n✓ Agent "${name}" created successfully!`)
  console.log(`\nNext steps:`)
  console.log(`  cd ${targetDir}`)
  console.log(`  rina test`)
  console.log(`  rina publish`)
}

/**
 * Parse CLI arguments for create command
 */
export function parseCreateArgs(args: string[]): CreateAgentOptions {
  const options: CreateAgentOptions = {
    name: '',
  }

  for (let i = 0; i < args.length; i++) {
    const arg = args[i]

    if (arg === '--name' && args[i + 1]) {
      options.name = args[++i]
    } else if (arg === '--description' && args[i + 1]) {
      options.description = args[++i]
    } else if (arg === '--author' && args[i + 1]) {
      options.author = args[++i]
    } else if (arg === '--permissions' && args[i + 1]) {
      options.permissions = args[++i].split(',')
    } else if (arg === '--output' && args[i + 1]) {
      options.outputDir = args[++i]
    } else if (!arg.startsWith('--')) {
      options.name = arg
    }
  }

  if (!options.name) {
    console.error('Error: Agent name is required')
    console.log('Usage: rina create-agent <name> [options]')
    process.exit(1)
  }

  return options
}

export default { createAgent, parseCreateArgs }
