/**
 * RinaWarp Share - Share Fix Plans
 *
 * Allows users to share their fix plans for viral growth.
 */

/**
 * Format a fix plan for sharing
 */
export function formatShareText(plan: string[]): string {
  return `
🔧 RinaWarp Fix Plan

${plan.join('\n')}

Generated by RinaWarp
https://rinawarptech.com
`.trim()
}

/**
 * Share a fix plan to clipboard
 * In browser context, this would use navigator.clipboard
 */
export async function shareFix(plan: string[]): Promise<{ success: boolean; message: string }> {
  const shareText = formatShareText(plan)

  // In Electron/renderer context
  if (typeof navigator !== 'undefined' && navigator.clipboard) {
    try {
      await navigator.clipboard.writeText(shareText)
      return {
        success: true,
        message:
          '✅ Fix plan copied to clipboard!\n\nShare it on:\n• GitHub issues\n• Slack\n• Discord\n• StackOverflow',
      }
    } catch (error: any) {
      return {
        success: false,
        message: `Failed to copy: ${error.message}\n\nHere's your fix plan:\n${shareText}`,
      }
    }
  }

  // Fallback - return the text to display
  return {
    success: true,
    message: `📋 Copy this to share:\n\n${shareText}`,
  }
}

/**
 * Generate a shareable error fix
 */
export function generateErrorShare(errorText: string, fix: string): string {
  return `
🚨 Error:
${errorText}

🔧 Fix:
${fix}

Generated by RinaWarp - AI Developer Assistant
https://rinawarptech.com
`.trim()
}
