import type { AgentPackage } from '../agent-manager.js'
import type { CapabilityPack } from './types.js'

export const BUILTIN_CAPABILITY_PACKS: CapabilityPack[] = [
  {
    key: 'system:doctor',
    title: 'System Doctor',
    description: 'Read-only diagnostics and guided repairs for system and workspace issues.',
    category: 'system',
    source: 'builtin',
    tier: 'starter',
    installState: 'builtin',
    permissions: ['read-only'],
    tags: ['doctor', 'diagnostics', 'proof'],
    actions: [
      { id: 'inspect', label: 'Inspect system state', tool: 'doctor.inspect', risk: 'read', proof: ['run', 'receipt', 'log'] },
      {
        id: 'repair',
        label: 'Apply guided repair',
        tool: 'doctor.fix',
        risk: 'safe-write',
        proof: ['run', 'receipt', 'log', 'artifact'],
        requiresConfirmation: true,
      },
    ],
  },
  {
    key: 'deploy:cloudflare',
    title: 'Cloudflare Deploy',
    description: 'Proof-backed deploy workflows for Workers, Pages, and related Cloudflare targets.',
    category: 'deploy',
    source: 'builtin',
    tier: 'pro',
    installState: 'builtin',
    permissions: ['read-only', 'workspace-write', 'network', 'cloud'],
    tags: ['deploy', 'cloudflare'],
    actions: [
      { id: 'plan', label: 'Plan deploy', tool: 'deploy.plan', risk: 'read', proof: ['run', 'receipt', 'log'] },
      {
        id: 'deploy',
        label: 'Deploy to Cloudflare',
        tool: 'deploy.cloudflare',
        risk: 'high-impact',
        proof: ['run', 'receipt', 'log', 'artifact'],
        requiresConfirmation: true,
      },
      { id: 'verify', label: 'Verify deploy', tool: 'deploy.verify', risk: 'read', proof: ['run', 'receipt', 'log', 'artifact'] },
      { id: 'rollback', label: 'Check rollback', tool: 'deploy.rollback', risk: 'high-impact', proof: ['run', 'receipt', 'log', 'artifact'] },
    ],
  },
  {
    key: 'deploy:vercel',
    title: 'Vercel Deploy',
    description: 'Proof-backed Vercel deploy workflows with target validation, verification, and rollback truth called out.',
    category: 'deploy',
    source: 'builtin',
    tier: 'pro',
    installState: 'builtin',
    permissions: ['read-only', 'workspace-write', 'network', 'cloud'],
    tags: ['deploy', 'vercel'],
    actions: [
      { id: 'plan', label: 'Plan deploy', tool: 'deploy.plan', risk: 'read', proof: ['run', 'receipt', 'log'] },
      { id: 'deploy', label: 'Deploy to Vercel', tool: 'deploy.vercel', risk: 'high-impact', proof: ['run', 'receipt', 'log', 'artifact'], requiresConfirmation: true },
      { id: 'verify', label: 'Verify deploy', tool: 'deploy.verify', risk: 'read', proof: ['run', 'receipt', 'log', 'artifact'] },
      { id: 'rollback', label: 'Check rollback', tool: 'deploy.rollback', risk: 'high-impact', proof: ['run', 'receipt', 'log', 'artifact'] },
    ],
  },
  {
    key: 'deploy:netlify',
    title: 'Netlify Deploy',
    description: 'Proof-backed Netlify deploy workflows with target validation, verification, and rollback truth called out.',
    category: 'deploy',
    source: 'builtin',
    tier: 'pro',
    installState: 'builtin',
    permissions: ['read-only', 'workspace-write', 'network', 'cloud'],
    tags: ['deploy', 'netlify'],
    actions: [
      { id: 'plan', label: 'Plan deploy', tool: 'deploy.plan', risk: 'read', proof: ['run', 'receipt', 'log'] },
      { id: 'deploy', label: 'Deploy to Netlify', tool: 'deploy.netlify', risk: 'high-impact', proof: ['run', 'receipt', 'log', 'artifact'], requiresConfirmation: true },
      { id: 'verify', label: 'Verify deploy', tool: 'deploy.verify', risk: 'read', proof: ['run', 'receipt', 'log', 'artifact'] },
      { id: 'rollback', label: 'Check rollback', tool: 'deploy.rollback', risk: 'high-impact', proof: ['run', 'receipt', 'log', 'artifact'] },
    ],
  },
  {
    key: 'deploy:docker',
    title: 'Docker Deploy',
    description: 'Proof-backed container deploy workflows with image validation, rollout verification, and rollback truth called out.',
    category: 'deploy',
    source: 'builtin',
    tier: 'pro',
    installState: 'builtin',
    permissions: ['read-only', 'workspace-write', 'network', 'cloud'],
    tags: ['deploy', 'docker'],
    actions: [
      { id: 'plan', label: 'Plan deploy', tool: 'deploy.plan', risk: 'read', proof: ['run', 'receipt', 'log'] },
      { id: 'deploy', label: 'Deploy container', tool: 'deploy.docker', risk: 'high-impact', proof: ['run', 'receipt', 'log', 'artifact'], requiresConfirmation: true },
      { id: 'verify', label: 'Verify deploy', tool: 'deploy.verify', risk: 'read', proof: ['run', 'receipt', 'log', 'artifact'] },
      { id: 'rollback', label: 'Check rollback', tool: 'deploy.rollback', risk: 'high-impact', proof: ['run', 'receipt', 'log', 'artifact'] },
    ],
  },
  {
    key: 'deploy:vps',
    title: 'VPS Deploy',
    description: 'Proof-backed SSH and VPS deploy workflows with host validation, verification, and explicit rollback truth.',
    category: 'deploy',
    source: 'builtin',
    tier: 'pro',
    installState: 'builtin',
    permissions: ['read-only', 'workspace-write', 'network', 'cloud'],
    tags: ['deploy', 'vps', 'ssh'],
    actions: [
      { id: 'plan', label: 'Plan deploy', tool: 'deploy.plan', risk: 'read', proof: ['run', 'receipt', 'log'] },
      { id: 'deploy', label: 'Deploy to VPS', tool: 'deploy.vps', risk: 'high-impact', proof: ['run', 'receipt', 'log', 'artifact'], requiresConfirmation: true },
      { id: 'verify', label: 'Verify deploy', tool: 'deploy.verify', risk: 'read', proof: ['run', 'receipt', 'log', 'artifact'] },
      { id: 'rollback', label: 'Check rollback', tool: 'deploy.rollback', risk: 'high-impact', proof: ['run', 'receipt', 'log', 'artifact'] },
    ],
  },
  {
    key: 'device:android:scan',
    title: 'Android Device Scan',
    description: 'ADB-backed Android inspection and evidence capture with explicit device permissions.',
    category: 'device',
    source: 'builtin',
    tier: 'pro',
    installState: 'available',
    permissions: ['read-only', 'device'],
    tags: ['android', 'adb', 'device'],
    actions: [
      { id: 'inspect', label: 'Scan Android device', tool: 'device.android.scan', risk: 'read', proof: ['run', 'receipt', 'log'] },
    ],
  },
  {
    key: 'device:ios:scan',
    title: 'iOS Device Scan',
    description: 'Limited iOS diagnostics with Apple-compatible tooling and strict approval boundaries.',
    category: 'device',
    source: 'builtin',
    tier: 'pro',
    installState: 'available',
    permissions: ['read-only', 'device'],
    tags: ['ios', 'device'],
    actions: [
      { id: 'inspect', label: 'Scan iOS device', tool: 'device.ios.scan', risk: 'read', proof: ['run', 'receipt', 'log'] },
    ],
  },
  {
    key: 'workspace:repo-audit',
    title: 'Workspace Repo Audit',
    description: 'Fast repository structure, file hot-spot, and workspace hygiene inspection with receipts attached.',
    category: 'workspace',
    source: 'builtin',
    tier: 'starter',
    installState: 'builtin',
    permissions: ['read-only'],
    tags: ['workspace', 'repo', 'audit'],
    actions: [
      { id: 'inspect', label: 'Inspect repository shape', tool: 'workspace.repo.audit', risk: 'read', proof: ['run', 'receipt', 'log'] },
    ],
  },
  {
    key: 'security:dependency-audit',
    title: 'Dependency Security Audit',
    description: 'Proof-backed dependency and secret exposure checks for repositories that need a quick risk readout.',
    category: 'security',
    source: 'builtin',
    tier: 'pro',
    installState: 'builtin',
    permissions: ['read-only', 'workspace-write'],
    tags: ['security', 'audit', 'dependencies'],
    actions: [
      { id: 'inspect', label: 'Run dependency audit', tool: 'security.dependency.audit', risk: 'read', proof: ['run', 'receipt', 'log', 'artifact'] },
    ],
  },
]

export const FALLBACK_MARKETPLACE_AGENTS: AgentPackage[] = [
  {
    name: 'deploy-helper',
    description: 'Common deployment helpers for Vercel, Netlify, and Docker',
    author: 'RinaWarp',
    version: '1.0.0',
    capability: {
      category: 'deploy',
      tier: 'paid',
      permissions: ['read-only', 'workspace-write', 'network', 'cloud'],
      risk: 'high-impact',
      tags: ['deploy', 'marketplace'],
      actions: [
        { id: 'vercel', label: 'Deploy to Vercel', risk: 'high-impact' },
        { id: 'netlify', label: 'Deploy to Netlify', risk: 'high-impact' },
        { id: 'docker', label: 'Deploy container', risk: 'high-impact' },
      ],
    },
    commands: [
      { name: 'vercel', steps: ['npm i -g vercel', 'vercel --prod'] },
      { name: 'netlify', steps: ['npm i -g netlify-cli', 'netlify deploy --prod'] },
      { name: 'docker', steps: ['docker build -t app .', 'docker push registry.example.com/app:latest'] },
    ],
    downloads: 0,
    price: 5,
  },
  {
    name: 'docker-cleanup',
    description: 'Clean up Docker resources - remove unused containers, images, and volumes',
    author: 'RinaWarp',
    version: '1.0.0',
    capability: {
      category: 'workspace',
      tier: 'paid',
      permissions: ['read-only', 'workspace-write'],
      risk: 'safe-write',
      tags: ['docker', 'cleanup', 'marketplace'],
      actions: [
        { id: 'clean', label: 'Clean Docker resources', risk: 'safe-write', requiresConfirmation: true },
        { id: 'status', label: 'Inspect Docker usage', risk: 'read' },
      ],
    },
    commands: [
      { name: 'clean', steps: ['docker system prune -af', 'docker volume prune -f'] },
      { name: 'status', steps: ['docker system df'] },
    ],
    downloads: 0,
    price: 3,
  },
  {
    name: 'security-audit',
    description: 'Run security audits on your project - npm audit, secrets detection, dependency checks',
    author: 'RinaWarp',
    version: '1.0.0',
    capability: {
      category: 'security',
      tier: 'paid',
      permissions: ['read-only', 'workspace-write'],
      risk: 'read',
      tags: ['security', 'audit', 'marketplace'],
      actions: [{ id: 'audit', label: 'Run security audit', risk: 'read', proof: ['run', 'receipt', 'log', 'artifact'] }],
    },
    commands: [{ name: 'audit', steps: ['npm audit --json > audit-report.json', 'cat audit-report.json | head -50'] }],
    downloads: 0,
    price: 5,
  },
  {
    name: 'system-diagnostics',
    description: 'Full system diagnostic agent. Collects logs, checks resource usage, and identifies common issues.',
    author: 'RinaWarp',
    version: '1.0.0',
    capability: {
      category: 'system',
      tier: 'starter',
      permissions: ['read-only'],
      risk: 'read',
      tags: ['diagnostics', 'system', 'marketplace'],
      actions: [{ id: 'diagnose', label: 'Run system diagnostics', risk: 'read' }],
    },
    commands: [{ name: 'diagnose', steps: ['df -h', 'free -m', 'top -bn1'] }],
    downloads: 0,
    price: 0,
  },
]
