apiVersion: v1
kind: Namespace
metadata:
  name: rinawarp-system
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: rinawarp-system
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: monitor
      port: 8222
      targetPort: 8222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: rinawarp-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.10-alpine
          args:
            - "-js"
            - "--sd=/data/jetstream"
            - "--http_port=8222"
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitor
          volumeMounts:
            - name: jetstream
              mountPath: /data/jetstream
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "500m"
              memory: 512Mi
      volumes:
        - name: jetstream
          emptyDir: {}
