name: Debug Simple

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Debug info
        run: |
          echo "Working directory: $(pwd)"
          echo "Node version: $(node -v)"
          ls -la
      - name: Success
        run: echo "Workflow completed successfully!"
