name: Lint

# Restrict permissions for security
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [ main ]  # Only main branch for production linting
  pull_request:
    branches: [ main, develop ]  # PRs for validation only

env:
  NODE_VERSION: "18"

jobs:
  lint:
    name: ESLint Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: Check code formatting
        run: npm run format:check
        continue-on-error: false

      - name: Lint Report
        if: failure()
        run: |
          echo "::error::Linting failed. Please fix the issues above and run 'npm run lint' locally to verify."
          echo "::error::You can also run 'npm run format' to auto-fix formatting issues."
          exit 1
