name: Nightly Builds

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Platforms to build for'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - windows
        - macos
        - linux

env:
  APP_NAME: "RinaWarp Terminal"
  NODE_VERSION: "18"

jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes in last 24 hours
        id: check
        run: |
          # For manual dispatch or schedule, always build
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.event_name }}" = "schedule" ]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "Manual trigger or scheduled run - will build"
            exit 0
          fi
          
          # For other triggers, check if there are any commits in the last 24 hours
          COMMITS=$(git log --since="24 hours ago" --oneline | wc -l)
          echo "Commits in last 24h: $COMMITS"
          
          if [ "$COMMITS" -gt 0 ]; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "Changes detected - will build"
          else
            echo "should_build=false" >> $GITHUB_OUTPUT
            echo "No changes in last 24h - skipping build"
          fi

  nightly-build:
    name: Nightly Build
    needs: check-changes
    if: needs.check-changes.outputs.should_build == 'true'
    
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win32
            arch: x64
            target: nsis,portable
            artifact_name: windows
            enabled: true
          - os: ubuntu-latest
            platform: linux
            arch: x64
            target: AppImage,deb
            artifact_name: linux
            enabled: true
          - os: macos-latest
            platform: darwin
            arch: x64
            target: dmg
            artifact_name: macos
            enabled: true

    runs-on: ${{ matrix.os }}
    if: ${{ matrix.enabled == true }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Platform-specific setup
      - name: Setup Windows
        if: matrix.os == 'windows-latest'
        run: |
          # Create self-signed certificate for nightly builds
          $cert = New-SelfSignedCertificate -Type CodeSigningCert -Subject "CN=RinaWarp Technologies (Nightly)" -KeyAlgorithm RSA -KeyLength 2048 -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" -KeyExportPolicy Exportable -KeyUsage DigitalSignature -CertStoreLocation Cert:\CurrentUser\My
          Export-PfxCertificate -Cert $cert -FilePath "rinawarp-codesign.pfx" -Password (ConvertTo-SecureString -String "RinaWarp2025!" -Force -AsPlainText)
        shell: pwsh

      - name: Setup Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm2 libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libxss-dev libasound2-dev

      # Update version for nightly
      - name: Update version for nightly
        run: |
          DATE=$(date +%Y%m%d)
          COMMIT=$(git rev-parse --short HEAD)
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NIGHTLY_VERSION="${CURRENT_VERSION}-nightly.${DATE}.${COMMIT}"
          
          echo "Updating version to: $NIGHTLY_VERSION"
          npm version $NIGHTLY_VERSION --no-git-tag-version
          
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "COMMIT=$COMMIT" >> $GITHUB_ENV
        shell: bash
        
      - name: Update product name for nightly (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          (Get-Content package.json) -replace '\"RinaWarp Terminal\"', '\"RinaWarp Terminal (Nightly)\"' | Set-Content package.json
        shell: pwsh
        
      - name: Update product name for nightly (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          sed -i 's/"RinaWarp Terminal"/"RinaWarp Terminal (Nightly)"/g' package.json
        shell: bash

      # Build the application
      - name: Build application (Windows)
        if: matrix.os == 'windows-latest'
        env:
          CSC_LINK: './rinawarp-codesign.pfx'
          CSC_KEY_PASSWORD: 'RinaWarp2025!'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:win
        shell: bash

      - name: Build application (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:linux
        shell: bash

      - name: Build application (macOS)
        if: matrix.os == 'macos-latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:mac
        shell: bash

      # Upload artifacts with date
      - name: Upload nightly artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-${{ matrix.artifact_name }}-${{ env.DATE }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
          retention-days: 14

  create-nightly-release:
    name: Create Nightly Release
    needs: [check-changes, nightly-build]
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.should_build == 'true'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate nightly tag
        id: tag
        run: |
          DATE=$(date +%Y%m%d)
          COMMIT=$(git rev-parse --short HEAD)
          TAG="nightly-${DATE}-${COMMIT}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

      # Download all nightly artifacts
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./nightly-release

      # Create nightly release
      - name: Create Nightly Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: RinaWarp Terminal Nightly ${{ steps.tag.outputs.date }}
          body: |
            # 🌙 Nightly Build - ${{ steps.tag.outputs.date }}
            
            This is an automated nightly build of RinaWarp Terminal.
            
            **⚠️ Disclaimer:** This is a development build and may contain bugs.
            
            ## What's New
            - Latest commits from the main branch
            - Development features and fixes
            
            ## Downloads
            - **Windows**: `.exe` installer and portable version
            - **Linux**: AppImage and DEB packages
            - **macOS**: DMG installer (unsigned)
            
            ## Installation Notes
            - Windows builds are code-signed with a development certificate
            - macOS builds are unsigned and will show security warnings
            - Linux builds work without additional setup
            
            ---
            
            Build from commit: ${{ github.sha }}
            
          files: ./nightly-release/**/*
          draft: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
