name: Performance Monitoring

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  performance:
    name: Performance Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build production bundle
      run: npm run build

    - name: Analyze bundle size
      run: npx bundlesize
      env:
        BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.11.x
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

    - name: Performance regression tests
      run: |
        npm run test:perf

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: |
          lighthouse-results/
          coverage/
          test-results/performance/
