name: Security

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security checks daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  NODE_VERSION: "18"

jobs:
  security-audit:
    name: Security Audit & Vulnerability Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm run security:check
        continue-on-error: false

      - name: Check for outdated packages
        run: npm outdated
        continue-on-error: true

      - name: Run vulnerability scan with Retire.js
        run: |
          npm install -g retire
          retire --path . --outputformat json --outputpath retire-report.json
        continue-on-error: true

      - name: Run ESLint security rules
        run: |
          npx eslint . --config .eslintrc.security.json --ext .js --format json --output-file eslint-security-report.json
        continue-on-error: true

      - name: Check for secrets in code
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --debug --only-verified

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports-${{ github.sha }}
          path: |
            retire-report.json
            eslint-security-report.json
          retention-days: 30

      - name: Security Report Summary
        if: failure()
        run: |
          echo "::error::Security checks failed. Please review the security issues above."
          echo "::error::Run 'npm run security:check' locally to investigate and fix issues."
          echo "::error::Consider running 'npm audit fix' to automatically fix some vulnerabilities."
          exit 1

  dependency-check:
    name: Dependency Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Analyze dependencies
        run: |
          echo "Analyzing package dependencies..."
          npm ls --depth=0
          echo "Package size analysis..."
          du -sh node_modules/ || true

      - name: Generate audit report
        run: |
          npm audit --json > audit-results.json || true
          npm audit --audit-level=moderate

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-audit-${{ github.sha }}
          path: audit-results.json
          retention-days: 30
